AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  HelloFunctionGR:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.handler
      Runtime: nodejs6.10
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Events:
        HelloTimeApiGR:
          Type: Api
          Properties:
            Path: /HelloResourceGR
            Method: GET
  GetCategoriesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/category/getCategories.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCategoriesApi:
          Type: Api
          Properties:
            Path: /categories
            Method: GET

  GetCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/category/getCategory.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCategoryApi:
          Type: Api
          Properties:
            Path: /categories/{id}
            Method: GET


  PostCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/category/postCategory.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        PostCategoryApi:
          Type: Api
          Properties:
            Path: /categories
            Method: POST

  # PutCategoryFunction:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Handler: lambdas/category/putCategory.handler
  #     Runtime: nodejs8.10
  #     CodeUri: ./src
  #     Policies: AmazonDynamoDBFullAccess
  #     Events:
  #       GetCategoryApi:
  #         Type: Api
  #         Properties:
  #           Path: /categories
  #           Method: PUT

  DeleteCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas/category/deleteCategory.handler
      Runtime: nodejs8.10
      CodeUri: ./src
      Policies: AmazonDynamoDBFullAccess
      Events:
        GetCategoryApi:
          Type: Api
          Properties:
            Path: /categories/{id}
            Method: DELETE