
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET
  PutData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: putData.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Events:
        MyTimeApiGR:
          Type: Api
          Properties:
            Path: /testDB
            Method: PUT
  GetData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getData.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Events:
        MyTimeApiGR:
          Type: Api
          Properties:
            Path: /testDB
            Method: GET
  CreateTestDB:
    Type: AWS::Serverless::Function
    Properties:
      Handler: createTable.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Policies: AmazonDynamoDBFullAccess
      Events:
        MyTimeApiGR:
          Type: Api
          Properties:
            Path: /testDB
            Method: GET